### ISSUE TITLE
软件没有识别出来图片旋转后的EXIF信息

### ISSUE THREAD

**Issue by Yonick2017** [xiaomingTang/img-handler#1]
使用版本：windows 可执行程序 0.0.1

原照片是方向错误的，使用看图软件旋转之后，其EXIF中Orientation值被改变，在此情况下进行拼接时会出现方向不对的问题
希望能够加入识别EXIF的照片方向，使用旋转后的照片进行拼接，谢谢！

**Comment by xiaomingTang** [comment]
@Yonick2017 感谢你的反馈，我会尽快确认并修复
