### ISSUE TITLE
图片顺序错误

### ISSUE THREAD

**Issue by FITHRPG6** [xiaomingTang/img-handler#2]
我按照程序提示选择2.按文件名一张一张排
![Snipaste_2021-08-18_17-18-10](https://user-images.githubusercontent.com/36270839/129873618-4fd7fd40-6b72-4bfb-821c-77c57d9d4026.png)
但是输出的结果却没有按照文件名的顺序排
![Snipaste_2021-08-18_17-21-50](https://user-images.githubusercontent.com/36270839/129873776-f1d19188-da76-4e33-86e4-2c2d08104881.png)

**Comment by xiaomingTang** [comment]
@FITHRPG6 抱歉才注意到，好像确实有bug，我没有对文件名进行重新排序，而是直接接受了系统传进的文件的顺序，所以出现文件排序错误，下个版本修复一下。
